Repository LdDl/video-server, pull requests merged in 2024-09, with the labels that each got.

#28 Allow user to better control threads
  streams.go
  streams_storage.go
Labels: enhancement

#32 Extend application configuration
  .gitignore
  README.md
  application.go
  cmd/video_server/conf.json
  cmd/video_server/main.go
  configuration/configuration.go
  docker-compose.yaml
  errors.go
  example_client/hls_example/package.json
  example_client/hls_example/src/App.vue
  example_client/mse_example/src/App.vue
  example_client/vanila_js/index.html
  go.mod
  go.sum
  hls.go
  http_server.go
  mp4.go
  scripts/minio-ansible.yml
  storage/archive_storage.go
  storage/filesystem.go
  storage/minio.go
  storage/storage_types.go
  stream.go
  stream_configuration.go
  stream_types.go
  streams.go
  streams_storage.go
  utils.go
  verbose.go
  video_server.go
  ws_handler.go
Labels: documentation, enhancement

#42 Log HTTP API
  http_server.go
  logger.go
  streams_storage.go
  ws_handler.go
Labels: enhancement, logs

#43 More logs stuff / Remove temporary MP4
  application.go
  cmd/video_server/conf.json
  configuration/configuration.go
  http_server.go
  logger.go
  mp4.go
  stream.go
  streams.go
  streams_storage.go
  video_server.go
  ws_handler.go
  ws_server.go
Labels: bug, logs

#44 Code structure changes + CORS Security issue
  application.go
  cmd/video_server/conf.json
  errors.go
  hls.go
  http_server.go
  logger.go
  mp4.go
  stream.go
  stream_types.go
  streams.go
  streams_storage.go
  utils.go
  ws_handler.go
Labels: documentation, enhancement, security

#45 More logging options / export archive wrapper
  application.go
  cmd/video_server/main.go
  hls.go
  logger.go
  mp4.go
  stream.go
  stream_archive.go
  stream_configuration.go
  streams.go
  streams_storage.go
  ws_handler.go
  ws_server.go
Labels: documentation, enhancement

#47 More verbosing
  application.go
  logger.go
  mp4.go
  streams_storage.go
Labels: logs

#48 Lock problem
  application.go
  cmd/video_server/main.go
  hls.go
  logger.go
  mp4.go
  storage/archive_storage.go
  storage/minio.go
  stream.go
  stream_hls.go
  stream_mp4.go
  streams.go
  streams_storage.go
Labels: bug
